//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARESUser
    {
        public CARESUser()
        {
            this.CARESUser1 = new HashSet<CARESUser>();
            this.Interactions = new HashSet<Interaction>();
            this.Events = new HashSet<Event>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserEmail { get; set; }
        public string UserPhoneNumber { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string UserStatus { get; set; }
        public string UserType { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
    
        public virtual ICollection<CARESUser> CARESUser1 { get; set; }
        public virtual CARESUser CARESUser2 { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<Interaction> Interactions { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
