//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interaction()
        {
            this.Interaction1 = new HashSet<Interaction>();
            this.InteractionServices = new HashSet<InteractionService>();
            this.Symptoms = new HashSet<Symptom>();
        }
    
        public int InteractionID { get; set; }
        public Nullable<int> ResidentID { get; set; }
        public Nullable<int> HealthWorkerID { get; set; }
        public Nullable<System.DateTime> DateOfContact { get; set; }
        public string MethodOfContact { get; set; }
        public string LocationOfContact { get; set; }
        public string COVIDTestLocation { get; set; }
        public string COVIDTestResult { get; set; }
        public string ActionPlan { get; set; }
        public Nullable<int> NewEditID { get; set; }
        public string EditReasonDateOfContact { get; set; }
        public string EditReasonMethodOfContact { get; set; }
        public string EditReasonLocationOfContact { get; set; }
        public string EditReasonActionPlan { get; set; }
        public string EditReasonTestLocation { get; set; }
        public string EditReasonTestResult { get; set; }
        public string EditReasonSymptoms { get; set; }
        public string EditReasonCriticalSymptoms { get; set; }
        public string EditReasonServicesOffered { get; set; }
        public string EditReasonServicesRequested { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
    
        public virtual CARESUser CARESUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interaction> Interaction1 { get; set; }
        public virtual Interaction Interaction2 { get; set; }
        public virtual Resident Resident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InteractionService> InteractionServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symptom> Symptoms { get; set; }
    }
}
