//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public Symptom()
        {
            this.Interactions = new HashSet<Interaction>();
        }
    
        public int SymptomID { get; set; }
        public string SymptomName { get; set; }
        public bool IsCritical { get; set; }
    
        public virtual ICollection<Interaction> Interactions { get; set; }
    }
}
